### ISSUE TITLE
jdp fails due to dirty git status

### ISSUE THREAD

**Issue by OmriRoames** [rened/DeclarativePackages.jl#10]
When building from source the git directory is not clean due to building artefacts. 

```
ERROR: LoadError: SubString{ASCIIString}["?? deps/builds/","?? deps/downloads/","?? deps/src/","?? deps/usr/"] -- Cannot create a jdp declaration from the currently installed packages as '/home/omri/.julia/declarative/lz8uzmbdIGia1Vtd3Ub1aw5Lde0bcIq6/v0.4/LibGEOS/LibGEOS' has local changes.
Please commit these changes, then run 'jdp' again.
 in error at ./error.jl:21
 in generatespecs at /home/omri/.julia/v0.4/DeclarativePackages/src/DeclarativePackages.jl:77
 in exportDECLARE at /home/omri/.julia/v0.4/DeclarativePackages/src/DeclarativePackages.jl:22
 in finish at /home/omri/.julia/v0.4/DeclarativePackages/src/installpackages.jl:228
 in installpackages at /home/omri/.julia/v0.4/DeclarativePackages/src/installpackages.jl:14
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/omri/.julia/v0.4/DeclarativePackages/src/installpackages.jl, in expression starting on line 253
```

The error arise from `git status -s` and the presence of the untracked files/dirs from the build. Changing git status to ignore untracked files fixes the problem. 

 `status = split(strip(readall($git status -s)), "\n")` -> `status = split(strip(readall($git status -uno)), "\n")`  in src/DeclarativePackages.jl line 72

**Comment by rened** [comment]
Yes, this does fix the problem, but I would prefer that packages exclude their build artifacts themselves. The files in `deps` are not standardized enough that we could reliably ignore only the machine specific files.

I believe it is important for the user to notice that certain files are not part of a valid commit. The resulting `DECLARE` file would not work anywhere else.

But thanks to you for looking into this!
