### ISSUE TITLE
Allow branch names alongside version / commit hash reference

### ISSUE THREAD

**Issue by r-chris** [rened/DeclarativePackages.jl#11]
It sometimes is useful to have a branch name referenced inside the `DECLARE` file, which will update along with that branch (example below).

``` bash
# Julia packages:  Packagename [ version or commit hash]
JSON
HDF5 0.4.6
Images 86a43d8368

# Any Git URL:  URL [ version or commit hash ]
https://github.com/JuliaLang/BinDeps.jl.git
https://github.com/timholy/HDF5.jl.git 0.4.6
https://github.com/jakebolewski/LibGit2.jl.git dcbf6f2419f92edeae4014f0a293c66a3c053671
https://github.com/timholy/Images.jl.git turbojpeg
```

**Comment by r-chris** [comment]
Resolved in https://github.com/rened/DeclarativePackages.jl/pull/13 (pending)

**Comment by JoshChristie** [comment]
The branch name gets updated to the latest commit in the `DECLARE` file after a run. Should the branch name be fixed unless it is manually changed in the `DECLARE`?

**Comment by r-chris** [comment]
I'm not 100% decided, but I am ok with the current behaviour - it's more clear at packaging time to have a commit hash over the branch name and makes things more reproducible. On the other hand keeping it fixed to the branch name is probably what we want.
